### ISSUE TITLE
create key figure widget component

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-insights#36]
### User story

> **As** dashboard viewer  
**I want** to see the most important KPIs prominently 
**So that** I find key information easily / quickly

### Acceptance criteria

- [ ] Show KPI value
- [ ] Show KPI unit
- [ ] Show KPI name
- [ ] Implement tooltip for description
- [ ] Rounding on given decimal point
- [ ] Scaling with a given factor (display unit)
- [ ] Handle missing data (display n/a ?)

**Comment by tibohei** [comment]
done with #13
