### ISSUE TITLE
enable react 18 when dependencies are ready

### ISSUE THREAD

**Issue by tibohei** [embrio-tech/centrifuge-insights#40]
### Why

- Use most recent version of react
- Remove warning
> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot

### What

Enable react 18 when dependency packages fully support it.

- Waiting for yocontra/react-responsive#293

### How

Change [`src/index.tsx`](https://github.com/embrio-tech/centrifuge-insights/blob/main/src/index.tsx)

- uncomment line 9-15
- remove line 17-22
- update imports accordingly

**Comment by yocontra** [comment]
@tibohei Should be fixed now FYI
