### ISSUE TITLE
add tranche(s) debt to pool development widget

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-insights#71]
### Accetance criteria
- split Pool NAV by tranche(s) -> add `trancheDebt` to pool development widget
- if Pool NAV <> Sum of all `trancheDebt` show residual (to be discussed if sensible)

**Comment by tibohei** [comment]
⚠️  subquery silently cuts queried documents to `limit=100` even if query requests `limit=1000`. This can lead to missing values if period is too long. How should wie handle this?

#### Subquery code 

[Code](https://github.com/subquery/subql/blob/e2e6b9731f37877f044dfdc8b6af7bd207105cca/packages/query/src/graphql/plugins/PgConnectionArgFirstLastBeforeAfter.ts#L29) responsible for this issue.

#### Example

![Screen Shot 2022-10-04 at 12 05 37](https://user-images.githubusercontent.com/16650977/193792852-7e02edb8-b1bf-444c-8305-2b62a5828809.png)
