### ISSUE TITLE
Implement rounding in widgets

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-insights#87]
### User story

> **As** dashboard viewer  
**I want** to see rounded values  
**So that** I am not distracted by irrelevant (micro-)amounts 

### Acceptance criteria

-> Dennis to look for/send the rounding rules applied in the CFG app -> let's align with these

![image](https://user-images.githubusercontent.com/52602184/188877300-ea0db6c1-4d70-4a3a-a449-5b2847009e46.png)
- [ ] Replace capital K as abbreviation for kilo with lowercase k

![image](https://user-images.githubusercontent.com/52602184/188877543-23ff6be1-6ac9-4c04-a0c0-16b1729d5dc6.png)
- [ ] Replace capital K as abbreviation for kilo with lowercase k

![image](https://user-images.githubusercontent.com/52602184/188877889-7c63c09a-277a-487e-afbe-d7c2e4f043b0.png)
- [ ] Replace capital K as abbreviation for kilo with lowercase k
- [ ] Show no decimals for percentages in legend (except when decimals are not zero, then show max. 2 decimals)

![image](https://user-images.githubusercontent.com/52602184/188878236-2fd2d67a-5416-4c5a-b9c2-440a8403f31a.png)
- [ ] Replace capital K as abbreviation for kilo with lowercase k
- [ ] Show max. 1 decimal for percentages
- [ ] Show max. 2 decimals for absolute values in legend (except when decimals are zero, then do not show decimals)
- [ ] Show no decimals for percentages in legend (except when decimals are not zero, then show max. 2 decimals)

![image](https://user-images.githubusercontent.com/52602184/188879132-e98d4f5d-0057-4f8c-94bc-3afa925d3b19.png)
- [ ] Show max. 2 decimals for absolute values in legend (except when decimals are zero, then do not show decimals) + unify decimals across legend

**Comment by tibohei** [comment]
Implemented:
- percentages in legend: round to 1 decimal
- percentages in chart: round to 2 decimal
- don't show trailing zeros in decimal (neither for percentages nor for currency)
