### ISSUE TITLE
show pool value widget

### ISSUE THREAD

**Issue by sandford-ch** [embrio-tech/centrifuge-insights#90]
### User story

> **As** dashboard viewer 
**I want** to see the total pool value 
**So that** I know how much is invested in any given pool

### Acceptance criteria
- [x] key figure widget showing Pool Value (TVL) as name
- [x] show `poolState/value` (latest total pool value)
- [x] round/minimize value so it fits 

### unrelated AC
- [x] Rename 'assetVolume`KPI widget to show "Asset Volume (NAV)"

**Comment by tibohei** [comment]
@sandford-ch the _AssetVolume (NAV)_ widget displays `totalEverBorrowed` as value. The label _(NAV)_ makes the user believe to see `netAssetValue`.

How should we resolve that confusion?

**Comment by sandford-ch** [comment]
Good point - in this case please rename to `Total borrowings`
